

# try {

# } cacht (err) {

# }


try:
    print("hola", usuario)
    print("hola")
    print("hola")
except Exception as error:
    print("error detectado", error)
    print("error detectado")
finally:
    print("final del control try / except")